import { useState, useEffect } from 'react'
import { Sun, Moon, Languages, FileText } from 'lucide-react'

const translations = {
  en: {
    title: 'OSPF LSA Reference',
    subtitle: 'Interactive reference for all OSPF LSA types: who generates them, their scope, fields and purpose.',
    selectLsa: 'Select LSA Type',
    description: 'Description',
    generatedBy: 'Generated By',
    scope: 'Flooding Scope',
    keyFields: 'Key Fields',
    diagram: 'Diagram',
    area: 'Area',
    as: 'Autonomous System',
    references: 'References',
    refList: ['RFC 2328 - OSPF Version 2', 'RFC 3101 - OSPF NSSA Option'],
    builtBy: 'Built by',
    lsas: {
      t1: {
        label: 'Type 1 - Router LSA',
        shortLabel: 'Type 1',
        description: 'Describes all the router\'s interfaces and their states within an area. Every OSPF router generates one Type 1 LSA per area it belongs to.',
        generatedBy: 'Every OSPF router (one per area)',
        scope: 'Area-local (not flooded beyond ABRs)',
        fields: ['Link State ID = Router ID', 'V-bit: Virtual link endpoint', 'E-bit: ASBR', 'B-bit: ABR', 'Links: list of router links (point-to-point, transit, stub, virtual)'],
        diagram: ['[Router A] -- generates --> [Type 1 LSA]', '  Link State ID = RID of Router A', '  Flooded within Area X only'],
      },
      t2: {
        label: 'Type 2 - Network LSA',
        shortLabel: 'Type 2',
        description: 'Generated by the Designated Router (DR) on broadcast and NBMA networks. Describes the set of routers attached to the network.',
        generatedBy: 'Designated Router (DR) on multi-access networks',
        scope: 'Area-local (not flooded beyond ABRs)',
        fields: ['Link State ID = IP address of the DR interface', 'Network Mask', 'List of attached routers (Router IDs)'],
        diagram: ['[DR] -- generates --> [Type 2 LSA]', '  Link State ID = DR interface IP', '  Lists all routers on segment', '  Flooded within Area X only'],
      },
      t3: {
        label: 'Type 3 - Summary Network LSA',
        shortLabel: 'Type 3',
        description: 'Generated by ABRs to advertise networks from one area into another. Used to build inter-area routes.',
        generatedBy: 'Area Border Router (ABR)',
        scope: 'Flooded into all areas (except stub/totally stub)',
        fields: ['Link State ID = Network address being advertised', 'Network Mask', 'Metric (cost to the network)'],
        diagram: ['[Area 1] --> [ABR] --> [Area 0] --> [ABR] --> [Area 2]', '  ABR generates Type 3 for each prefix in Area 1', '  Type 3 is flooded into Area 0 and Area 2'],
      },
      t4: {
        label: 'Type 4 - Summary ASBR LSA',
        shortLabel: 'Type 4',
        description: 'Generated by ABRs to advertise the location (Router ID) of an ASBR to other areas. Allows routers to find the path to ASBRs in remote areas.',
        generatedBy: 'Area Border Router (ABR)',
        scope: 'Flooded into all areas except the ASBR\'s own area',
        fields: ['Link State ID = Router ID of the ASBR', 'Network Mask = 0.0.0.0', 'Metric (cost to reach the ASBR)'],
        diagram: ['[ASBR in Area 1] -- advertised by --> [ABR as Type 4]', '  Type 4 flooded into Area 0 and all other areas', '  Allows external route resolution (Type 5)'],
      },
      t5: {
        label: 'Type 5 - AS-External LSA',
        shortLabel: 'Type 5',
        description: 'Generated by ASBRs to advertise routes from outside the OSPF domain. Flooded throughout the entire AS except stub areas.',
        generatedBy: 'Autonomous System Boundary Router (ASBR)',
        scope: 'AS-wide (entire OSPF domain, except stub/NSSA areas)',
        fields: ['Link State ID = External network address', 'Network Mask', 'Metric Type: E1 (internal+external cost) or E2 (external cost only)', 'Forwarding Address', 'External Route Tag'],
        diagram: ['[External BGP/Static] --> [ASBR] --> [Type 5 LSA]', '  Flooded to all non-stub areas', '  E1: metric = internal cost + external metric', '  E2: metric = external metric only (default)'],
      },
      t7: {
        label: 'Type 7 - NSSA External LSA',
        shortLabel: 'Type 7',
        description: 'Used in NSSA areas as a replacement for Type 5 LSAs. Generated by ASBRs inside an NSSA. ABRs translate Type 7 to Type 5 when flooding to other areas.',
        generatedBy: 'ASBR inside an NSSA area',
        scope: 'NSSA area only (ABR translates to Type 5 at area boundary)',
        fields: ['Link State ID = External network address', 'Network Mask', 'Metric Type: N1 or N2 (analogous to E1/E2)', 'Forwarding Address (mandatory, unlike Type 5)', 'P-bit: if set, ABR translates Type 7 to Type 5'],
        diagram: ['[External Route] --> [ASBR in NSSA] --> [Type 7 LSA]', '  Flooded within NSSA area only', '  [ABR] translates Type 7 --> Type 5 for other areas', '  P-bit must be set for translation'],
      },
    },
  },
  pt: {
    title: 'Referencia de LSA OSPF',
    subtitle: 'Referencia interativa para todos os tipos de LSA do OSPF: quem os gera, escopo, campos e proposito.',
    selectLsa: 'Selecione o Tipo de LSA',
    description: 'Descricao',
    generatedBy: 'Gerado Por',
    scope: 'Escopo de Inundacao',
    keyFields: 'Campos Principais',
    diagram: 'Diagrama',
    area: 'Area',
    as: 'Sistema Autonomo',
    references: 'Referencias',
    refList: ['RFC 2328 - OSPF Versao 2', 'RFC 3101 - Opcao NSSA do OSPF'],
    builtBy: 'Criado por',
    lsas: {
      t1: {
        label: 'Tipo 1 - LSA de Roteador',
        shortLabel: 'Tipo 1',
        description: 'Descreve todas as interfaces do roteador e seus estados dentro de uma area. Todo roteador OSPF gera um LSA Tipo 1 por area a que pertence.',
        generatedBy: 'Todo roteador OSPF (um por area)',
        scope: 'Local a area (nao inundado alem dos ABRs)',
        fields: ['Link State ID = ID do Roteador', 'Bit V: endpoint de link virtual', 'Bit E: ASBR', 'Bit B: ABR', 'Links: lista de links do roteador (ponto-a-ponto, transito, stub, virtual)'],
        diagram: ['[Roteador A] -- gera --> [LSA Tipo 1]', '  Link State ID = RID do Roteador A', '  Inundado apenas dentro da Area X'],
      },
      t2: {
        label: 'Tipo 2 - LSA de Rede',
        shortLabel: 'Tipo 2',
        description: 'Gerado pelo Roteador Designado (DR) em redes broadcast e NBMA. Descreve o conjunto de roteadores conectados a rede.',
        generatedBy: 'Roteador Designado (DR) em redes multi-acesso',
        scope: 'Local a area (nao inundado alem dos ABRs)',
        fields: ['Link State ID = Endereco IP da interface do DR', 'Mascara de Rede', 'Lista de roteadores conectados (Router IDs)'],
        diagram: ['[DR] -- gera --> [LSA Tipo 2]', '  Link State ID = IP da interface do DR', '  Lista todos os roteadores no segmento', '  Inundado apenas dentro da Area X'],
      },
      t3: {
        label: 'Tipo 3 - LSA Sumario de Rede',
        shortLabel: 'Tipo 3',
        description: 'Gerado pelos ABRs para anunciar redes de uma area para outra. Usado para construir rotas inter-area.',
        generatedBy: 'Roteador de Borda de Area (ABR)',
        scope: 'Inundado em todas as areas (exceto stub/totalmente stub)',
        fields: ['Link State ID = Endereco de rede anunciado', 'Mascara de Rede', 'Metrica (custo ate a rede)'],
        diagram: ['[Area 1] --> [ABR] --> [Area 0] --> [ABR] --> [Area 2]', '  ABR gera Tipo 3 para cada prefixo na Area 1', '  Tipo 3 e inundado na Area 0 e Area 2'],
      },
      t4: {
        label: 'Tipo 4 - LSA Sumario ASBR',
        shortLabel: 'Tipo 4',
        description: 'Gerado pelos ABRs para anunciar a localizacao (Router ID) de um ASBR para outras areas. Permite que roteadores encontrem o caminho ate ASBRs remotos.',
        generatedBy: 'Roteador de Borda de Area (ABR)',
        scope: 'Inundado em todas as areas exceto a propria area do ASBR',
        fields: ['Link State ID = Router ID do ASBR', 'Mascara de Rede = 0.0.0.0', 'Metrica (custo ate o ASBR)'],
        diagram: ['[ASBR na Area 1] -- anunciado por --> [ABR como Tipo 4]', '  Tipo 4 inundado na Area 0 e demais areas', '  Permite resolucao de rotas externas (Tipo 5)'],
      },
      t5: {
        label: 'Tipo 5 - LSA Externo AS',
        shortLabel: 'Tipo 5',
        description: 'Gerado pelos ASBRs para anunciar rotas de fora do dominio OSPF. Inundado por todo o AS, exceto areas stub.',
        generatedBy: 'Roteador de Fronteira do Sistema Autonomo (ASBR)',
        scope: 'Todo o AS (exceto areas stub/NSSA)',
        fields: ['Link State ID = Endereco da rede externa', 'Mascara de Rede', 'Tipo de Metrica: E1 (custo interno+externo) ou E2 (somente custo externo)', 'Endereco de Encaminhamento', 'Tag de Rota Externa'],
        diagram: ['[BGP/Estatico Externo] --> [ASBR] --> [LSA Tipo 5]', '  Inundado para todas as areas nao-stub', '  E1: metrica = custo interno + metrica externa', '  E2: metrica = somente metrica externa (padrao)'],
      },
      t7: {
        label: 'Tipo 7 - LSA Externo NSSA',
        shortLabel: 'Tipo 7',
        description: 'Usado em areas NSSA como substituto dos LSAs Tipo 5. Gerado por ASBRs dentro de uma NSSA. ABRs traduzem Tipo 7 para Tipo 5 ao inundar para outras areas.',
        generatedBy: 'ASBR dentro de uma area NSSA',
        scope: 'Somente area NSSA (ABR traduz para Tipo 5 na fronteira)',
        fields: ['Link State ID = Endereco da rede externa', 'Mascara de Rede', 'Tipo de Metrica: N1 ou N2 (analogos ao E1/E2)', 'Endereco de Encaminhamento (obrigatorio, diferente do Tipo 5)', 'Bit P: se definido, ABR traduz Tipo 7 para Tipo 5'],
        diagram: ['[Rota Externa] --> [ASBR na NSSA] --> [LSA Tipo 7]', '  Inundado apenas dentro da area NSSA', '  [ABR] traduz Tipo 7 --> Tipo 5 para outras areas', '  Bit P deve estar definido para traducao'],
      },
    },
  },
} as const

type Lang = keyof typeof translations
type LsaKey = 't1' | 't2' | 't3' | 't4' | 't5' | 't7'

const LSA_KEYS: LsaKey[] = ['t1', 't2', 't3', 't4', 't5', 't7']

const LSA_COLORS: Record<LsaKey, { tab: string; badge: string; dot: string }> = {
  t1: { tab: 'bg-blue-500', badge: 'bg-blue-500/15 text-blue-600 dark:text-blue-400 border-blue-500/30', dot: 'bg-blue-500' },
  t2: { tab: 'bg-cyan-500', badge: 'bg-cyan-500/15 text-cyan-600 dark:text-cyan-400 border-cyan-500/30', dot: 'bg-cyan-500' },
  t3: { tab: 'bg-indigo-500', badge: 'bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 border-indigo-500/30', dot: 'bg-indigo-500' },
  t4: { tab: 'bg-violet-500', badge: 'bg-violet-500/15 text-violet-600 dark:text-violet-400 border-violet-500/30', dot: 'bg-violet-500' },
  t5: { tab: 'bg-red-500', badge: 'bg-red-500/15 text-red-600 dark:text-red-400 border-red-500/30', dot: 'bg-red-500' },
  t7: { tab: 'bg-orange-500', badge: 'bg-orange-500/15 text-orange-600 dark:text-orange-400 border-orange-500/30', dot: 'bg-orange-500' },
}

export default function OspfLsaReference() {
  const [lang, setLang] = useState<Lang>(() => (navigator.language.startsWith('pt') ? 'pt' : 'en'))
  const [dark, setDark] = useState(() => window.matchMedia('(prefers-color-scheme: dark)').matches)
  const [selected, setSelected] = useState<LsaKey>('t1')

  const t = translations[lang]
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])

  const lsa = t.lsas[selected]
  const colors = LSA_COLORS[selected]

  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-[#09090b] text-zinc-900 dark:text-zinc-100 transition-colors">
      <header className="border-b border-zinc-200 dark:border-zinc-800 px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-indigo-500 rounded-lg flex items-center justify-center">
              <FileText size={18} className="text-white" />
            </div>
            <span className="font-semibold">OSPF LSA Reference</span>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={() => setLang(l => l === 'en' ? 'pt' : 'en')} className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors">
              <Languages size={14} />{lang.toUpperCase()}
            </button>
            <button onClick={() => setDark(d => !d)} className="p-2 rounded-lg border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors">
              {dark ? <Sun size={16} /> : <Moon size={16} />}
            </button>
            <a href="https://github.com/gmowses/ospf-lsa-reference" target="_blank" rel="noopener noreferrer" className="p-2 rounded-lg border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"/></svg>
            </a>
          </div>
        </div>
      </header>

      <main className="flex-1 px-6 py-10">
        <div className="max-w-5xl mx-auto space-y-8">
          <div>
            <h1 className="text-3xl font-bold">{t.title}</h1>
            <p className="mt-2 text-zinc-500 dark:text-zinc-400">{t.subtitle}</p>
          </div>

          {/* Tab selector */}
          <div className="flex flex-wrap gap-2">
            {LSA_KEYS.map(key => {
              const lsaData = t.lsas[key]
              const isSelected = selected === key
              return (
                <button
                  key={key}
                  onClick={() => setSelected(key)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium border transition-all ${
                    isSelected
                      ? `${LSA_COLORS[key].tab} text-white border-transparent`
                      : 'border-zinc-200 dark:border-zinc-800 hover:bg-zinc-100 dark:hover:bg-zinc-800'
                  }`}
                >
                  {lsaData.shortLabel}
                </button>
              )
            })}
          </div>

          {/* Detail card */}
          <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 overflow-hidden">
            <div className={`${colors.tab} px-6 py-4`}>
              <h2 className="text-white font-bold text-lg">{lsa.label}</h2>
            </div>
            <div className="p-6 grid gap-6 lg:grid-cols-2">
              <div className="space-y-5">
                <div>
                  <h3 className="text-xs uppercase tracking-wide text-zinc-400 font-medium mb-2">{t.description}</h3>
                  <p className="text-sm leading-relaxed">{lsa.description}</p>
                </div>

                <div>
                  <h3 className="text-xs uppercase tracking-wide text-zinc-400 font-medium mb-2">{t.generatedBy}</h3>
                  <div className={`inline-flex items-center gap-1.5 text-sm font-medium px-3 py-1.5 rounded-lg border ${colors.badge}`}>
                    <span className={`w-2 h-2 rounded-full ${colors.dot}`} />
                    {lsa.generatedBy}
                  </div>
                </div>

                <div>
                  <h3 className="text-xs uppercase tracking-wide text-zinc-400 font-medium mb-2">{t.scope}</h3>
                  <p className="text-sm text-zinc-600 dark:text-zinc-400">{lsa.scope}</p>
                </div>
              </div>

              <div className="space-y-5">
                <div>
                  <h3 className="text-xs uppercase tracking-wide text-zinc-400 font-medium mb-2">{t.keyFields}</h3>
                  <ul className="space-y-1.5">
                    {lsa.fields.map((field, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm">
                        <span className={`w-1.5 h-1.5 rounded-full mt-1.5 shrink-0 ${colors.dot}`} />
                        <span className="text-zinc-600 dark:text-zinc-400">{field}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="text-xs uppercase tracking-wide text-zinc-400 font-medium mb-2">{t.diagram}</h3>
                  <div className="rounded-lg bg-zinc-950 text-zinc-100 p-4 font-mono text-xs space-y-1">
                    {lsa.diagram.map((line, i) => (
                      <div key={i} className="leading-relaxed">{line}</div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Quick summary table */}
          <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 overflow-x-auto">
            <h2 className="font-semibold mb-4">{t.selectLsa}</h2>
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="border-b border-zinc-200 dark:border-zinc-800">
                  <th className="text-left py-2 pr-4 text-xs uppercase tracking-wide text-zinc-400 font-medium w-24">Type</th>
                  <th className="text-left py-2 pr-4 text-xs uppercase tracking-wide text-zinc-400 font-medium">{t.generatedBy}</th>
                  <th className="text-left py-2 text-xs uppercase tracking-wide text-zinc-400 font-medium">{t.scope}</th>
                </tr>
              </thead>
              <tbody>
                {LSA_KEYS.map(key => {
                  const row = t.lsas[key]
                  return (
                    <tr
                      key={key}
                      onClick={() => setSelected(key)}
                      className={`border-b border-zinc-100 dark:border-zinc-800/60 cursor-pointer transition-colors ${selected === key ? 'bg-zinc-50 dark:bg-zinc-800/50' : 'hover:bg-zinc-50 dark:hover:bg-zinc-800/30'}`}
                    >
                      <td className="py-2 pr-4">
                        <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-2 py-0.5 rounded border ${LSA_COLORS[key].badge}`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${LSA_COLORS[key].dot}`} />
                          {row.shortLabel}
                        </span>
                      </td>
                      <td className="py-2 pr-4 text-xs text-zinc-600 dark:text-zinc-400">{row.generatedBy}</td>
                      <td className="py-2 text-xs text-zinc-500 dark:text-zinc-500">{row.scope}</td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>

          <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6">
            <h2 className="font-semibold mb-3">{t.references}</h2>
            <ul className="space-y-1">
              {t.refList.map(ref => (
                <li key={ref} className="text-sm text-zinc-500 dark:text-zinc-400 flex items-start gap-2">
                  <span className="text-indigo-500 mt-0.5">•</span>{ref}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </main>

      <footer className="border-t border-zinc-200 dark:border-zinc-800 px-6 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between text-xs text-zinc-400">
          <span>{t.builtBy} <a href="https://github.com/gmowses" className="text-zinc-600 dark:text-zinc-300 hover:text-indigo-500 transition-colors">Gabriel Mowses</a></span>
          <span>MIT License</span>
        </div>
      </footer>
    </div>
  )
}
